CREATE DATABASE COPPEL;
USE COPPEL;

CREATE TABLE CLIENTES(
  ID_CLIENTE CHAR(8) PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(50)NOT NULL,
  TELEFONO CHAR(10)UNIQUE,
  DIRECCION VARCHAR(150)
);

CREATE TABLE PROVEEDORES(
  ID_PROVEEDOR CHAR(8) PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(50),
  TELEFONO CHAR(10)NOT NULL UNIQUE,
  DIRECCION VARCHAR(150)
);

CREATE TABLE CATEGORIAS(
  ID_CATEGORIA CHAR(8) PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(50)
);

CREATE TABLE PRODUCTOS(
  ID_PRODUCTO CHAR(8) PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(50),
  PRECIO DOUBLE(10,2)NOT NULL CHECK (PRECIO >= 0),
  ID_CATEGORIA CHAR(8),
  ID_PROVEEDOR CHAR(8),
  FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
  FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE EMPLEADOS(
  ID_EMPLEADO CHAR(8) PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(50),
  ROL VARCHAR(50)NOT NULL,
  TELEFONO CHAR(10)UNIQUE,
  DIRECCION VARCHAR(150)
);
CREATE TABLE VENTAS(
  ID_VENTA CHAR(8) PRIMARY KEY,
  FECHA DATE,
  DESCUENTO DOUBLE(10,2),
  PAGO_TOTAL DOUBLE(10,2) NOT NULL CHECK (PAGO_TOTAL >= 0),
  ID_CLIENTE CHAR(8),
  ID_EMPLEADO CHAR(8),
  ID_PRODUCTO CHAR(8),
  FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
  FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
  FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE CREDITOS(
  ID_CREDITO CHAR(8) PRIMARY KEY NOT NULL,
  ID_CLIENTE CHAR(8),
  PAGO_TOTAL DOUBLE(10,2)NOT NULL,
  PAGOS_RESTANTES INT,
  ESTATUS VARCHAR(50)NOT NULL,
  FECHA_INICIO DATE,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE PAGOS(
  ID_PAGO CHAR(8) PRIMARY KEY NOT NULL,
  ID_CREDITO CHAR(8)NOT NULL,
  FECHA DATE,
  PAGO DOUBLE(10,2)NOT NULL,
  METODO_PAGO VARCHAR(50),
  FOREIGN KEY (ID_CREDITO) REFERENCES CREDITOS(ID_CREDITO)
);
